steps:
  # Step 1: Build the Docker image using secret
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker.io/$_DOCKER_USERNAME/comfy-with-wan2.1-cnet:$BUILD_ID', '.']
    secretEnv: ['DOCKER_USERNAME']
  # Step 2: Authenticate with Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USERNAME" --password-stdin
    env:
      - 'DOCKER_USERNAME=$_DOCKER_USERNAME'
      - 'DOCKER_PASSWORD=$_DOCKER_PASSWORD'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
  # Step 3: Push the Docker image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'docker.io/$_DOCKER_USERNAME/comfy-with-wan2.1-cnet:$BUILD_ID']
    secretEnv: ['DOCKER_USERNAME']
availableSecrets:
  secretManager:
    - versionName: projects/$remote-docker-push/secrets/docker-username/versions/latest
      env: DOCKER_USERNAME
    - versionName: projects/$remote-docker-push/secrets/docker-password/versions/latest
      env: DOCKER_PASSWORD
