steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker.io/$DOCKER_USERNAME/my-repo:$BUILD_ID', '.']
    # Step 2: Authenticate with Docker Hub using secrets
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USERNAME" --password-stdin
      env:
        - 'DOCKER_USERNAME=$$DOCKER_USERNAME'
        - 'DOCKER_PASSWORD=$$DOCKER_PASSWORD'
      secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
    # Step 3: Push the Docker image to Docker Hub
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'docker.io/$DOCKER_USERNAME/my-repo:$BUILD_ID']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/latest
      env: DOCKER_USERNAME
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/latest
      env: DOCKER_PASSWORD
