steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker.io/can9ai/comfy-with-wan2.1-cnet:latest', '.']
  # Step 2: Authenticate with Docker Hub using secrets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USERNAME" --password-stdin
    env:
      - 'DOCKER_USERNAME=$$DOCKER_USERNAME'
      - 'DOCKER_PASSWORD=$$DOCKER_PASSWORD'
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
  # Step 3: Push the Docker image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'docker.io/can9ai/comfy-with-wan2.1-cnet:latest']
availableSecrets:
  secretManager:
    - versionName: projects/remote-docker-push/secrets/docker-username/versions/latest
      env: DOCKER_USERNAME
    - versionName: projects/remote-docker-push/secrets/docker-password/versions/latest
      env: DOCKER_PASSWORD
